### ISSUE TITLE
inter.c, function inter_proc bogus condition

### ISSUE THREAD

**Issue by chris1879** [mubastan/mpeg7fex#5]
Hi,

In file inter.c line 497 the if and else if are bogus because the same condition.
Certainly the second else if should be  "_i_in2channels" (second)

BR,
Christian

  if (!reschannels) {
    if (_i_in1channels) {
      width=_i_in1width-in1posx;
      height=_i_in1height-in1posy;
    }
    else if (_i_in1channels) {
      width=_i_in2width-in1posx;
      height=_i_in2height-in1posy;
    }
    else {
      addlib_stop_here("Warning : no image componenet given\n",0,0);
      return;
    }
    resposx=0;
    resposy=0;
  }

**Comment by mubastan** [comment]
I think, you are right. But I have not tested it.
I do not know if this part of the code is used in the MPEG-7 feature extraction.

This code seems to be more than 20 years old! :)
It is also rather messy, with lots of meaningless variable names, like the rest of the XM Software :(
However, I am still thankful, since they shared the code, even though it is messy and buggy; otherwise, it would have taken a long time to develop from scratch.
