### ISSUE TITLE
Usage of the Contour Shape Descriptor

### ISSUE THREAD

**Issue by mkgmxgit** [mubastan/mpeg7fex#9]
Hello Muhammet,

first of all thanks for this good repo. It makes the calculation and use of the MPEG7 descriptors much easier. Very good work.
I have a question about the contour shape descriptors.
Do you have an example how to correctly output the Contour Shape Descriptor to the console? Is the calculated size of the descriptor fixed or does it vary depending on how many peaks are in the contour. Do you know what the individual components mean?
I cannot pass a whole frame to the descriptor, but only a mask with the object contour, if I have understood it correctly, or?

Thanks a lot for the help and best regards
Michael

**Comment by mubastan** [comment]
Hello Michael,

Thanks for your interest.

Honestly speaking, it has been about 10 years since I last worked on this project (except dealing with some github issues here); so, I have forgotten most of the things :(

It seems the current test codes under test/main.cpp and test/FexWrite.cpp do not include the countour shape descriptor output. I do not know if it is available somewhere.
However, it should not be difficult to write it by looking at the ContourShape descriptor class (Descriptors/ContourShape.h and Descriptors/ContourShape.cpp), particularly the commented ExportDDL and ImportDDL functions.
I will be more than happy to receive a pull request about it :)

For descriptor details, I would recommend the following book, if you can find it:
B. S. Manjunath, P. Salembier, and T. Sikora, Introduction to MPEG-7: Multimedia Content Description Interface. England: WILEY, 2002.

Papers:
Bober, M. (2001). MPEG-7 visual shape descriptors. IEEE Transactions on Circuits and Systems for Video Technology, 11(6), 716-719

Hope this helps.

**Comment by mkgmxgit** [comment]
Hello Muhammet,

thanks for the quick response and the helpful links to the book and the paper.
Yes exactly, the test code under test/main.cpp and test/FexWrite unfortunately did not contain an example for the contour shape descriptor and I didn't find an example anywhere else. 
I'll try to generate an example for the CShD and if I'm successful, I'll gladly make a pull request ;)
Maybe we can leave the issue open in the meantime if someone else has suggestions, explanations or even code examples for the contour shape descriptor.

Kind regards
Michael
